#! /usr/bin/env bash

# Code for managing sgriege's personal dotfiles.
# Copyright (C) 2026 Simon Grieger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

source 'lib/dotfiles.sh'

# All paths below are relative to the home directory. The script must be run from the top-level
# directory of the git repository.

dotfiles_clean_dir  '.config/htop'
dotfiles_clean_dir  '.emacs.lisp'
dotfiles_clean_file 'bin/get-time'
dotfiles_clean_file 'bin/run-rsync-for-backup'
dotfiles_clean_file 'bin/run-rsync-for-backup-silently'
dotfiles_clean_file 'bin/run-rsync-for-backup-with-overall-progress'
dotfiles_clean_file 'bin/run-rsync-for-backup-with-verbose-progress'

dotfiles_make_dir 'tmp'
dotfiles_install_all
gmake -C tools
